# KNU CSE 2021114026 Jeongwoo Kim
# Libraries below written by: 2023011393 Nawon Kim, KNU CSE 2021114026 Jeongwoo Kim, 2023013565 Dahye Jeong
# Phony target: "refresh": deletes all of (pre)compiled files

.PHONY: refresh

pln_sv: plnit_serverCore.c
	gcc -o pln_sv plnit_serverCore.c -g

refresh:
	rm pln_sv